### ISSUE TITLE
seems to not work with dynamic libraries

### ISSUE THREAD

**Issue by TaxMachine** [ac3ss0r/obfusheader.h#2]
I get this error message with my code
`'decryptor' cannot be thread local when declared 'dllexport'`

```cpp
#include "obfusheader.h"
#include <jni.h>

extern "C" JNIEXPORT void JNICALL dev_taxmachine_testobf_Main_test(JNIEnv *env, jobject obj) {
    const char* text = OBF("Hello from C++!"); // the error in here on the OBF() macro
    DYNAMIC_HIDE_CALL(&printf, text);
}
```

**Comment by ac3ss0r** [comment]
You can check the new updates version. It has call hiding completely remade, now it's a lot more stable & safe. 
```C++
CALL(&printf, "Hello from C++");
```

**Comment by ac3ss0r** [comment]
Also considering your error be sure to use normal encryption mode, not THREADLOCAL. That seems to be a compiler limitation
```C++
#define CONST_ENCRYPT_MODE          NORMAL
```

**Comment by TaxMachine** [comment]
Alright thanks, I'll try it
