### ISSUE TITLE
Fake-Sig help

### ISSUE THREAD

**Issue by alnicke** [ac3ss0r/obfusheader.h#4]
can you provide a usage of fake sig?

**Comment by 90th** [comment]
it acts as a decoy.

**Comment by ac3ss0r** [comment]
> can you provide a usage of fake sig?



> can you provide a usage of fake sig?

Whenever you enable it upon compiling fake signatures will be added to the binary automatically. Those signatures are detected by DIE (detect-it-easy) and other popular softwares. This way you can trick reverse-engineers into thinking your binary was protected with multiple big protectors, such as Themida, VMProtect, SecuROM, etc
