### ISSUE TITLE
Watermark/Fake sig doesn't apply

### ISSUE THREAD

**Issue by LionHackerman** [ac3ss0r/obfusheader.h#5]
When compiling with your test application, the watermark and fake signature features do not work. If I drop it in DetectItEasy (latest version), it doesn't show any protectors and in IDA Pro, the watermark isn't in the flow graphs.

Do I need to disable some compiler features? I've disabled whole program optimization so far...

**Comment by LionHackerman** [comment]
> For the Fake sig ac3ss0r has already answered this. and for the watermark to show I believe you need to do some call hiding for example CALL(printf, "hello world");
> 
> ![fcDJilK](https://private-user-images.githubusercontent.com/80871202/342442600-acdb872f-207e-4852-abe6-284e0e56a5ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNjkzMTgsIm5iZiI6MTcxOTI2OTAxOCwicGF0aCI6Ii84MDg3MTIwMi8zNDI0NDI2MDAtYWNkYjg3MmYtMjA3ZS00ODUyLWFiZTYtMjg0ZTBlNTZhNWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDIyNDMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MzA4Y2U4NWQwNGM5MTFhMWY3OWUzZGIxZGNkY2Q3YzdhMzVmZDY0MmZkM2UxMTQ5MTJiNjdhMjRhNThhYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5tjOw-FiDL6LjG1Orne4swObWx3RmPl2UUMK02y15m0)

I've already disabled WPO and I used the example code which includes numerous "CALL"s

**Comment by 90th** [comment]
And did you make sure to enable it in the config?

**Comment by LionHackerman** [comment]
Yep. I tried with default settings, enabling most options (not kernel). Not too sure why it isn't working...

**Comment by 90th** [comment]
![qsm2t88](https://github.com/ac3ss0r/obfusheader.h/assets/80871202/8ca6f9e4-1a9d-43fd-b5a2-b8bd18bbf212)

Works fine for me.
